// Generated by gencpp from file moving_core/LocalizePart.msg
// DO NOT EDIT!


#ifndef MOVING_CORE_MESSAGE_LOCALIZEPART_H
#define MOVING_CORE_MESSAGE_LOCALIZEPART_H

#include <ros/service_traits.h>


#include <moving_core/LocalizePartRequest.h>
#include <moving_core/LocalizePartResponse.h>


namespace moving_core
{

struct LocalizePart
{

typedef LocalizePartRequest Request;
typedef LocalizePartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LocalizePart
} // namespace moving_core


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moving_core::LocalizePart > {
  static const char* value()
  {
    return "aa4cca5b67ec8a13449c405ec10ee5d0";
  }

  static const char* value(const ::moving_core::LocalizePart&) { return value(); }
};

template<>
struct DataType< ::moving_core::LocalizePart > {
  static const char* value()
  {
    return "moving_core/LocalizePart";
  }

  static const char* value(const ::moving_core::LocalizePart&) { return value(); }
};


// service_traits::MD5Sum< ::moving_core::LocalizePartRequest> should match 
// service_traits::MD5Sum< ::moving_core::LocalizePart > 
template<>
struct MD5Sum< ::moving_core::LocalizePartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moving_core::LocalizePart >::value();
  }
  static const char* value(const ::moving_core::LocalizePartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moving_core::LocalizePartRequest> should match 
// service_traits::DataType< ::moving_core::LocalizePart > 
template<>
struct DataType< ::moving_core::LocalizePartRequest>
{
  static const char* value()
  {
    return DataType< ::moving_core::LocalizePart >::value();
  }
  static const char* value(const ::moving_core::LocalizePartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moving_core::LocalizePartResponse> should match 
// service_traits::MD5Sum< ::moving_core::LocalizePart > 
template<>
struct MD5Sum< ::moving_core::LocalizePartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moving_core::LocalizePart >::value();
  }
  static const char* value(const ::moving_core::LocalizePartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moving_core::LocalizePartResponse> should match 
// service_traits::DataType< ::moving_core::LocalizePart > 
template<>
struct DataType< ::moving_core::LocalizePartResponse>
{
  static const char* value()
  {
    return DataType< ::moving_core::LocalizePart >::value();
  }
  static const char* value(const ::moving_core::LocalizePartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVING_CORE_MESSAGE_LOCALIZEPART_H
